name: Build IWRT x86-64

# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: 'specify a luci version to build'
        required: false
        default: '24.10.3'
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Build targets x86-64 inside docker container
        run: |
          echo "start to build x86 64"
          docker run --rm -i -u root \
            -v ${{ github.workspace }}/bin:/home/build/immortalwrt/bin \
            -v ${{ github.workspace }}/build.sh:/opt/build.sh \
            immortalwrt/imagebuilder:x86-64-openwrt-${{ inputs.luci_version }} /bin/bash /opt/build.sh

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "🍏 This job's status is ${{ job.status }}."


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # create a release based on a file from runner workspace 
      - name: Create Release
        uses: softprops/action-gh-release@v2.4.0
        with:
          # tag_name: IWRT-builder
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
          body_path: ${{ github.workspace }}/release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

